spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=pizzariabomgosto;integratedSecurity=false;encrypt=false;trustServerCerticate=true
    username: sa
    password: '@ITB123456'
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
